// <auto-generated />
using ExpanseTrackerApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpanseTrackerApp.Migrations
{
    [DbContext(typeof(ExpanseDbContext))]
    partial class ExpanseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpanseTrackerApp.Entities.Expanse", b =>
                {
                    b.Property<int>("ExpanseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpanseId"));

                    b.Property<int>("Grocery")
                        .HasColumnType("int");

                    b.Property<int>("HouseRant")
                        .HasColumnType("int");

                    b.Property<int>("Utility")
                        .HasColumnType("int");

                    b.HasKey("ExpanseId");

                    b.ToTable("Expanses");
                });

            modelBuilder.Entity("ExpanseTrackerApp.Entities.Login", b =>
                {
                    b.Property<int>("LoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ExpanseTrackerApp.Entities.Login", b =>
                {
                    b.HasOne("ExpanseTrackerApp.Entities.Expanse", "Expanse")
                        .WithOne("Login")
                        .HasForeignKey("ExpanseTrackerApp.Entities.Login", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expanse");
                });

            modelBuilder.Entity("ExpanseTrackerApp.Entities.Expanse", b =>
                {
                    b.Navigation("Login")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
